"""name must be unique per user

Revision ID: 8e4c2eaa5c76
Revises: f16f61c0db05
Create Date: 2026-03-22 15:02:28.643277

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e4c2eaa5c76'
down_revision: str | Sequence[str] | None = 'f16f61c0db05'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    # Load all accounts
    accounts = conn.execute(sa.text("SELECT id, user_id, name FROM accounts ORDER BY user_id, name")).fetchall()

    # Track seen names per user
    seen = {}
    for account in accounts:
        user_id = account.user_id
        name = account.name
        if user_id not in seen:
            seen[user_id] = {}
        if name not in seen[user_id]:
            seen[user_id][name] = 1
        else:
            # Duplicate found, create new name with suffix
            i = seen[user_id][name]
            new_name = f"{name}_{i}"
            seen[user_id][name] += 1

            # Ensure new_name is unique for this user
            while new_name in seen[user_id]:
                i += 1
                new_name = f"{name}_{i}"
                seen[user_id][name] = i + 1

            # Update the account in DB
            conn.execute(
                sa.text("UPDATE accounts SET name = :new_name WHERE id = :id"),
                {"new_name": new_name, "id": account.id}
            )
            seen[user_id][new_name] = 1

    # Now add the unique constraint safely
    op.create_unique_constraint('uq_user_account_name', 'accounts', ['user_id', 'name'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_account_name', 'accounts', type_='unique')
    # ### end Alembic commands ###
