"""name must be unique per account

Revision ID: f13993518e39
Revises: 8e4c2eaa5c76
Create Date: 2026-03-22 19:22:49.214206

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f13993518e39'
down_revision: str | Sequence[str] | None = '8e4c2eaa5c76'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()

    # Load all categories ordered by account + name
    categories = conn.execute(
        sa.text("SELECT id, account_id, name FROM categories ORDER BY account_id, name")
    ).fetchall()

    # Track seen names per account
    seen = {}

    for category in categories:
        account_id = category.account_id
        name = category.name

        if account_id not in seen:
            seen[account_id] = {}

        if name not in seen[account_id]:
            seen[account_id][name] = 1
        else:
            # Duplicate found → rename with suffix
            i = seen[account_id][name]
            new_name = f"{name}_{i}"
            seen[account_id][name] += 1

            # Ensure uniqueness within this account
            while new_name in seen[account_id]:
                i += 1
                new_name = f"{name}_{i}"
                seen[account_id][name] = i + 1

            # Update DB
            conn.execute(
                sa.text("UPDATE categories SET name = :new_name WHERE id = :id"),
                {"new_name": new_name, "id": category.id},
            )

            seen[account_id][new_name] = 1

    # Add constraint after cleanup
    op.create_unique_constraint(
        'uq_account_category_name',
        'categories',
        ['account_id', 'name']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_account_category_name', 'categories', type_='unique')
    # ### end Alembic commands ###
