// TODO: IMPLEMENT HERE DATA CONSTANTS FROM DATABASE STRUCTURE OF TABLES AND API RETURNS
// TODO: THEN USE THEMS INSIDE THE 'ApplicationShell' COMPONENT
// TODO: HANDLE ROUTING AND CHECKING IF THERE IS A SESSION TO REDIRECT
